backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "content/images"

collections:
  - name: "services" # Used in routes, e.g., /admin/collections/content
    label: "Sekce" # Used in the UI
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/services/services.md'
        label: 'Služby'
        name: 'services-page'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ServicesPage,
            }
          - { label: Slug, name: slug, widget: hidden, default: 'services-page' }
          - { label: Titulek, name: title, widget: string }
          - label: 'Služby'
            name: 'services'
            widget: 'list'
            required: false
            fields:
              - { label: 'Nadpis', name: 'title', widget: 'string' }
              - { label: Ikona, name: icon, widget: text }
              - label: Text, 
                name: text, 
                widget: list
                fields: 
                - { label: 'Nabízené služby', name: 'service', widget: 'string' }