backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_library:
  name: uploadcare
  config:
    publicKey: a73a170cb5cdef662983
    multiple: false
    tabs: 'file camera url facebook gdrive'
    effects: 'crop,rotate,enhance,grayscale'
    imageShrink: '2000x2000'
    previewStep: true
    clearable: true

collections:
  - name: "section" # Used in routes, e.g., /admin/collections/blog
    label: "Sekce" # Used in the UI
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: 'content/data/pageData.yaml'
        label: 'Hlavička'
        name: 'header'
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: LandingPage,
            }
          - { label: Titulek, name: welcomeText, widget: string }